export const PACKAGE_TYPES: PackageType[] = [
  {
    id: '1',
    name: 'الباقات الشاملة',
    slug: 'comprehensive',
    description: 'فحوصات متكاملة تغطي جميع الجوانب الصحية الأساسية',
    badgeColor: 'blue',
    icon: 'activity',
    thumbnailUrl: '/package-types/comprehensive-hero.png',
    displayOrder: 1,
    isActive: true,
  },
  {
    id: '2',
    name: 'الباقات المختصة',
    slug: 'specialized',
    description: 'تحاليل مركّزة لحالات صحية محددة — هرمونات، حساسية، سكري',
    badgeColor: 'violet',
    icon: 'microscope',
    displayOrder: 2,
    isActive: true,
  },
  {
    id: '3',
    name: 'الصحة الجنسية',
    slug: 'sexual-health',
    description: 'فحوصات سرية وآمنة للأمراض المنقولة — خصوصية تامة',
    badgeColor: 'pink',
    icon: 'heart-pulse',
    displayOrder: 3,
    isActive: true,
  },
  {
    id: '4',
    name: 'باقة الزواج',
    slug: 'marriage',
    description: 'فحوصات ما قبل الزواج معتمدة في صحتي — زيارة منزلية مجانية',
    badgeColor: 'teal',
    icon: 'heart-handshake',
    thumbnailUrl: '/package-types/marriage-banner.png',
    displayOrder: 4,
    isActive: true,
  },
  {
    id: '5',
    name: 'التحاليل الجينية',
    slug: 'genetic',
    description: 'اطمئني على صحة جنينك من الأسبوع العاشر بفحص دم بسيط — آمن 100% ودقة تتجاوز 99%',
    badgeColor: 'teal',
    icon: 'dna',
    displayOrder: 5,
    isActive: true,
  },
  {
    id: '6',
    name: 'العروض',
    slug: 'offers',
    description: 'أسعار حصرية لفترة محدودة — اغتنم الفرصة',
    badgeColor: 'amber',
    icon: 'badge-percent',
    displayOrder: 6,
    isActive: true,
  },
]

export const PACKAGE_CATEGORIES: PackageCategory[] = [
  // Comprehensive packages categories
  {
    id: '1',
    name: 'استكشافية',
    slug: 'exploratory',
  },
  {
    id: '2',
    name: 'متقدمة',
    slug: 'advanced',
  },
  {
    id: '3',
    name: 'رويال للرجال',
    slug: 'men',
  },
  {
    id: '4',
    name: 'رويال للنساء',
    slug: 'women',
  },

  // Specialized packages categories
  {
    id: '5',
    name: 'هرمونات',
    slug: 'hormones',
  },
  {
    id: '6',
    name: 'حساسية',
    slug: 'allergy',
  },
  {
    id: '7',
    name: 'دم وسيولة',
    slug: 'blood',
  },
  {
    id: '8',
    name: 'كبد وكلى',
    slug: 'liver',
  },
  {
    id: '9',
    name: 'سكري',
    slug: 'diabetes',
  },
  {
    id: '10',
    name: 'هضمي وتغذية',
    slug: 'digestive',
  },
  {
    id: '11',
    name: 'فيتامينات',
    slug: 'vitamins',
  },
]

export const PACKAGES: Package[] = [
  {
    id: '1',
    packageTypeId: '1',
    packageCategoryId: '1',
    name: 'الباقة الاستكشافية',
    slug: 'exploratory',
    description: 'فحص شامل للحالة الصحية العامة — مثالية للبداية',
    price: 600,
    discountedPrice: 299,
    badge: 'الأساسية',
    thumbnailUrl: '/packages/comprehensive.jpg',
    displayOrder: 1,
    isActive: true,
  },
  {
    id: '2',
    packageTypeId: '1',
    packageCategoryId: '1',
    name: 'الباقة الاستكشافية بلس',
    slug: 'exploratory_plus',
    description: 'كل تحاليل الاستكشافية + فحوصات إضافية متقدمة',
    price: 800,
    discountedPrice: 399,
    badge: 'متميزة',
    thumbnailUrl: '/packages/comprehensive.jpg',
    displayOrder: 2,
    isActive: true,
  },
  {
    id: '3',
    packageTypeId: '1',
    packageCategoryId: '2',
    name: 'الباقة المتقدمة',
    slug: 'advanced',
    description: 'فحص معمق مع دلالات الأورام وسيولة الدم',
    price: 1400,
    discountedPrice: 699,
    badge: 'متقدمة',
    thumbnailUrl: '/packages/comprehensive.jpg',
    displayOrder: 3,
    isActive: true,
  },
  {
    id: '4',
    packageTypeId: '1',
    packageCategoryId: '2',
    name: 'الباقة المتقدمة بلس',
    slug: 'advanced_plus',
    description: 'الباقة الأشمل — كل التحاليل مع الأمراض المعدية',
    price: 1800,
    discountedPrice: 899,
    badge: 'الأكثر طلباً',
    thumbnailUrl: '/packages/comprehensive.jpg',
    displayOrder: 4,
    isActive: true,
  },
  {
    id: '5',
    packageTypeId: '1',
    packageCategoryId: '3',
    name: 'باقة الرويال للرجال',
    slug: 'royal_men',
    description: 'باقة شاملة للرجال مع فحص البروستات والهرمونات',
    price: 2000,
    discountedPrice: 999,
    badge: 'للرجال',
    thumbnailUrl: '/packages/comprehensive.jpg',
    displayOrder: 5,
    isActive: true,
  },
  {
    id: '6',
    packageTypeId: '1',
    packageCategoryId: '3',
    name: 'باقة الرويال للرجال بلس',
    slug: 'royal_men_plus',
    description: 'الباقة الأكثر شمولاً للرجال مع الأمراض المعدية',
    price: 2600,
    discountedPrice: 1299,
    badge: 'للرجال — برميوم',
    thumbnailUrl: '/packages/comprehensive.jpg',
    displayOrder: 6,
    isActive: true,
  },
  {
    id: '7',
    packageTypeId: '1',
    packageCategoryId: '4',
    name: 'باقة الرويال للنساء',
    slug: 'royal_women',
    description: 'باقة شاملة للمرأة مع الهرمونات والنساء',
    price: 2000,
    discountedPrice: 999,
    badge: 'للنساء',
    thumbnailUrl: '/packages/comprehensive.jpg',
    displayOrder: 7,
    isActive: true,
  },
  {
    id: '8',
    packageTypeId: '1',
    packageCategoryId: '4',
    name: 'باقة الرويال للنساء بلس',
    slug: 'royal_women_plus',
    description: 'الأشمل للمرأة — 85+ تحليل مع دلالات الأورام',
    price: 3800,
    discountedPrice: 1899,
    badge: 'للنساء — برميوم',
    thumbnailUrl: '/packages/comprehensive.jpg',
    displayOrder: 8,
    isActive: true,
  },
  {
    id: '9',
    packageTypeId: '2',
    packageCategoryId: '10',
    name: 'تحليل الروكوتان',
    slug: 'rokutan',
    description:
      'فحوصات متخصصة قبل وخلال استخدام دواء الروكوتان — تشمل وظائف الكبد والكلى والدهون وفحص الحمل',
    price: 300,
    discountedPrice: 149,
    badge: 'متخصصة',
    thumbnailUrl: '/packages/spec-rokutan.webp',
    displayOrder: 1,
    isActive: true,
  },
  {
    id: '10',
    packageTypeId: '2',
    packageCategoryId: '7',
    name: 'باقة سيولة الدم',
    slug: 'coag',
    description: 'تحاليل شاملة لمعرفة حالة سيولة وتخثر الدم — تشمل PT وPTT وINR وصورة الدم الكاملة',
    price: 320,
    discountedPrice: 149,
    badge: 'دم',
    thumbnailUrl: '/packages/spec-coag.webp',
    displayOrder: 2,
    isActive: true,
  },
  {
    id: '11',
    packageTypeId: '2',
    name: 'باقة صحة العظام',
    slug: 'bones',
    description:
      'كالسيوم وفيتامين D والفوسفور والمغنيسيوم مع إنزيم الفوسفاتيز وتحليل الروماتيزم وصورة الدم',
    price: 350,
    discountedPrice: 199,
    badge: 'متخصصة',
    thumbnailUrl: '/packages/spec-bones.webp',
    displayOrder: 3,
    isActive: true,
  },
  {
    id: '12',
    packageTypeId: '2',
    packageCategoryId: '8',
    name: 'باقة صحة الكلى والمسالك',
    slug: 'kidney',
    description: 'تقييم وظائف الكلى — الكرياتينين ومعدل الترشيح واليوريا وحمض البوريك وتحليل البول',
    price: 350,
    discountedPrice: 199,
    badge: 'كبد وكلى',
    thumbnailUrl: '/packages/spec-kidney.webp',
    displayOrder: 4,
    isActive: true,
  },
  {
    id: '13',
    packageTypeId: '2',
    packageCategoryId: '8',
    name: 'باقة صحة الكبد',
    slug: 'liver',
    description:
      'فحص شامل لإنزيمات الكبد والصفراء والبروتينات الكبدية وسيولة الدم — 14 تحليل معمّق',
    price: 499,
    discountedPrice: 249,
    badge: 'كبد وكلى',
    thumbnailUrl: '/packages/spec-liver.webp',
    displayOrder: 5,
    isActive: true,
  },
  {
    id: '14',
    packageTypeId: '2',
    packageCategoryId: '9',
    name: 'باقة متابعة السكري',
    slug: 'diabetes',
    description: 'متابعة دقيقة للسكر التراكمي والصائم والأنسولين ومقاومة الأنسولين مع صورة الدم',
    price: 499,
    discountedPrice: 249,
    badge: 'سكري',
    thumbnailUrl: '/packages/spec-diabetes.webp',
    displayOrder: 6,
    isActive: true,
  },
  {
    id: '15',
    packageTypeId: '2',
    packageCategoryId: '5',
    name: 'باقة الغدة الدرقية',
    slug: 'thyroid',
    description: 'تقييم وظيفة الغدة الدرقية — TSH وهرمون T3 الحر وT4 الحر مع صورة الدم الكاملة',
    price: 600,
    discountedPrice: 299,
    badge: 'هرمونات',
    thumbnailUrl: '/packages/spec-thyroid.webp',
    displayOrder: 7,
    isActive: true,
  },
  {
    id: '16',
    packageTypeId: '2',
    packageCategoryId: '7',
    name: 'باقة فقر الدم',
    slug: 'anemia',
    description:
      'تحاليل متكاملة لتحديد أسباب فقر الدم — الحديد ومخازنه وقدرة الارتباط مع الفيتامينات وصورة الدم',
    price: 500,
    discountedPrice: 299,
    badge: 'دم',
    thumbnailUrl: '/packages/spec-anemia.webp',
    displayOrder: 8,
    isActive: true,
  },
  {
    id: '17',
    packageTypeId: '2',
    packageCategoryId: '11',
    name: 'باقة الفيتامينات والمعادن الأساسية',
    slug: 'vitamins-basic',
    description: 'فحص أساسي لأهم 5 فيتامينات ومعادن — فيتامين D وB12 والفوليك أسيد والزنك والنحاس',
    price: 600,
    discountedPrice: 299,
    badge: 'فيتامينات',
    thumbnailUrl: '/',
    displayOrder: 9,
    isActive: true,
  },
  {
    id: '18',
    packageTypeId: '2',
    name: 'باقة الأطفال',
    slug: 'children',
    description:
      'فحوصات دورية شاملة لصحة الأطفال — وظائف الكبد والكلى والغدة والحديد والفيتامينات وصورة الدم',
    price: 699,
    discountedPrice: 349,
    badge: 'متخصصة',
    thumbnailUrl: '/packages/spec-children.webp',
    displayOrder: 10,
    isActive: true,
  },
  {
    id: '19',
    packageTypeId: '2',
    name: 'باقة متابعة الضغط',
    slug: 'bp',
    description:
      'تحاليل أساسية لمرضى الضغط — القلب والكلى والكبد والدهون والأملاح وصورة الدم الكاملة',
    price: 500,
    discountedPrice: 349,
    badge: 'متخصصة',
    thumbnailUrl: '/packages/spec-bp.webp',
    displayOrder: 11,
    isActive: true,
  },
  {
    id: '20',
    packageTypeId: '2',
    name: 'باقة فحص المسابح',
    slug: 'pool',
    description:
      'فحوصات الأمراض المعدية المطلوبة لدخول المسابح — HIV والتهاب الكبد B وC والزهري وتحليل البول',
    price: 699,
    discountedPrice: 349,
    badge: 'متخصصة',
    thumbnailUrl: '/packages/spec-pool.webp',
    displayOrder: 12,
    isActive: true,
  },
  {
    id: '21',
    packageTypeId: '2',
    name: 'باقة الشعر',
    slug: 'hair',
    description:
      'تحاليل تساقط الشعر — الحديد والزنك والمغنيسيوم والنحاس والفيتامينات والغدة الدرقية مع فحص الفطريات',
    price: 799,
    discountedPrice: 399,
    badge: 'متخصصة',
    thumbnailUrl: '/packages/spec-hair.webp',
    displayOrder: 13,
    isActive: true,
  },
  {
    id: '22',
    packageTypeId: '2',
    name: 'باقة الشقيقة والصداع',
    slug: 'migraine',
    description:
      'كشف الأسباب المخبرية وراء الصداع المزمن — الالتهابات والكلى والكبد والسكر والغدة والأملاح',
    price: 500,
    discountedPrice: 399,
    badge: 'متخصصة',
    thumbnailUrl: '/packages/spec-migraine.webp',
    displayOrder: 14,
    isActive: true,
  },
  {
    id: '23',
    packageTypeId: '2',
    packageCategoryId: '6',
    name: 'اختبار حساسية الاستنشاق',
    slug: 'allergy-inhalation',
    description: 'يغطي 34 من مسببات الحساسية التنفسية — غبار وعث وأشجار وحيوانات وعفن بتقنية IGE',
    price: 599,
    discountedPrice: 425,
    badge: 'حساسية',
    thumbnailUrl: '/packages/spec-allergy-inhalation.webp',
    displayOrder: 15,
    isActive: true,
  },
  {
    id: '24',
    packageTypeId: '2',
    packageCategoryId: '6',
    name: 'اختبار حساسية الطعام',
    slug: 'allergy-food',
    description: 'يغطي 38 من مسببات الحساسية الغذائية — حليب وبيض وقمح ومكسرات وأسماك بتقنية IGE',
    price: 599,
    discountedPrice: 425,
    badge: 'حساسية',
    thumbnailUrl: '/packages/spec-allergy-food.webp',
    displayOrder: 16,
    isActive: true,
  },
  {
    id: '25',
    packageTypeId: '2',
    packageCategoryId: '6',
    name: 'اختبار حساسية الأطفال',
    slug: 'allergy-pediatric',
    description: 'يغطي 28 من مسببات الحساسية التنفسية والغذائية للأطفال بتقنية IGE',
    price: 599,
    discountedPrice: 425,
    badge: 'حساسية',
    thumbnailUrl: '/packages/spec-allergy-pediatric.webp',
    displayOrder: 17,
    isActive: true,
  },
  {
    id: '26',
    packageTypeId: '2',
    packageCategoryId: '6',
    name: 'فحص الحساسية الشامل',
    slug: 'allergy-comprehensive',
    description: 'أشمل فحص — يغطي 55 من مسببات الحساسية التنفسية والغذائية معاً بتقنية IGE',
    price: 599,
    discountedPrice: 425,
    badge: 'حساسية',
    thumbnailUrl: '/packages/spec-allergy-atopy.webp',
    displayOrder: 18,
    isActive: true,
  },
  {
    id: '27',
    packageTypeId: '2',
    packageCategoryId: '5',
    name: 'باقة تكيس المبايض',
    slug: 'pcos',
    description:
      'تقييم هرمونات الإباضة والأندروجينات — FSH وLH والتستوستيرون والأنسولين والغدة الدرقية',
    price: 999,
    discountedPrice: 449,
    badge: 'هرمونات',
    thumbnailUrl: '/packages/spec-pcos.webp',
    displayOrder: 19,
    isActive: true,
  },
  {
    id: '28',
    packageTypeId: '2',
    packageCategoryId: '10',
    name: 'باقة الجهاز الهضمي والقولون',
    slug: 'digestive',
    description:
      'تقييم شامل لصحة القناة الهضمية — تحليل البراز والمزارع وجرثومة المعدة والدم الخفي ودلالات الأورام',
    price: 999,
    discountedPrice: 499,
    badge: 'هضمي',
    thumbnailUrl: '/packages/spec-digestive.webp',
    displayOrder: 20,
    isActive: true,
  },
  {
    id: '29',
    packageTypeId: '2',
    packageCategoryId: '9',
    name: 'باقة السمنة وثبات الوزن',
    slug: 'obesity',
    description:
      'تقييم الأسباب الهرمونية لثبات الوزن — الغدة والسكر والأنسولين والدهون والكبد والأملاح',
    price: 1000,
    discountedPrice: 499,
    badge: 'سكري',
    thumbnailUrl: '/packages/spec-obesity.webp',
    displayOrder: 21,
    isActive: true,
  },
  {
    id: '30',
    packageTypeId: '2',
    name: 'باقة الكسل والخمول',
    slug: 'fatigue',
    description:
      'اكتشف أسباب التعب المزمن — الغدة الدرقية والسكر والفيتامينات والمعادن الأساسية وصورة الدم',
    price: 1000,
    discountedPrice: 499,
    badge: 'متخصصة',
    thumbnailUrl: '/packages/spec-fatigue.webp',
    displayOrder: 22,
    isActive: true,
  },
  {
    id: '31',
    packageTypeId: '2',
    packageCategoryId: '5',
    name: 'باقة خصوبة الرجل',
    slug: 'male-fertility',
    description:
      'تقييم شامل لهرمونات الخصوبة — التستوستيرون والحويصلات المنوية وتحليل السائل المنوي والمزارع',
    price: 800,
    discountedPrice: 499,
    badge: 'هرمونات',
    thumbnailUrl: '/packages/spec-male-fertility.webp',
    displayOrder: 23,
    isActive: true,
  },
  {
    id: '32',
    packageTypeId: '2',
    name: 'باقة فحص ماقبل العمليات',
    slug: 'pre-op',
    description:
      'الفحوصات الإلزامية قبل أي تدخل جراحي — سيولة الدم وفصيلة الدم والسكر والكبد والكلى والأمراض المعدية',
    price: 850,
    discountedPrice: 499,
    badge: 'متخصصة',
    thumbnailUrl: '/packages/spec-pre-op.webp',
    displayOrder: 24,
    isActive: true,
  },
  {
    id: '33',
    packageTypeId: '2',
    packageCategoryId: '10',
    name: 'باقة حساسية القمح',
    slug: 'gluten',
    description:
      'فحص الحساسية للغلوتين والقمح — اختبار السيلياك والأجسام المضادة والالتهابات وصورة الدم',
    price: 850,
    discountedPrice: 499,
    badge: 'هضمي',
    thumbnailUrl: '/packages/spec-gluten.webp',
    displayOrder: 25,
    isActive: true,
  },
  {
    id: '34',
    packageTypeId: '2',
    name: 'باقة التكميم',
    slug: 'sleeve',
    description:
      'فحوصات ما قبل وبعد عملية التكميم — الكلى والكبد والغدة والدهون والأملاح والفيتامينات الشاملة',
    price: 800,
    discountedPrice: 599,
    badge: 'متخصصة',
    thumbnailUrl: '/packages/spec-sleeve.webp',
    displayOrder: 26,
    isActive: true,
  },
  {
    id: '35',
    packageTypeId: '2',
    packageCategoryId: '5',
    name: 'باقة خصوبة المرأة',
    slug: 'female-fertility',
    description:
      'تقييم مخزون البويضات — الاستراديول وFSH وLH وهرمون الحليب وجودة البويضات والأنسولين والغدة',
    price: 1199,
    discountedPrice: 599,
    badge: 'هرمونات',
    thumbnailUrl: '/packages/spec-female-fertility.webp',
    displayOrder: 27,
    isActive: true,
  },
  {
    id: '36',
    packageTypeId: '2',
    packageCategoryId: '11',
    name: 'باقة الفيتامينات والمعادن المتقدمة',
    slug: 'vitamins-advanced',
    description:
      'مسح شامل لـ 14 فيتامين ومعدن — فيتامين D وB12 والفوليك والحديد والزنك والكالسيوم والمغنيسيوم',
    price: 800,
    discountedPrice: 599,
    badge: 'فيتامينات',
    thumbnailUrl: '/packages/spec-vitamins-adv.webp',
    displayOrder: 28,
    isActive: true,
  },
  {
    id: '37',
    packageTypeId: '2',
    name: 'باقة النضارة والجمال',
    slug: 'beauty',
    description:
      'فحوصات داخلية لدعم صحة البشرة — الدم والدهون والكبد والأملاح والسكر والفيتامينات والغدة والكلى والشعر',
    price: 1299,
    discountedPrice: 649,
    badge: 'متخصصة',
    thumbnailUrl: '/packages/spec-beauty.webp',
    displayOrder: 29,
    isActive: true,
  },
  {
    id: '38',
    packageTypeId: '2',
    name: 'باقة فحص الزواج',
    slug: 'marriage-test',
    description: 'فحص الزواج المعتمد في منصة صحتي — تحاليل إلزامية شاملة للشخص الواحد. قبل التأمين',
    price: 699,
    badge: 'متخصصة',
    thumbnailUrl: '/packages/spec-marriage.webp',
    displayOrder: 30,
    isActive: true,
  },
  {
    id: '39',
    packageTypeId: '2',
    packageCategoryId: '5',
    name: 'باقة متابعة الحمل',
    slug: 'pregnancy',
    description:
      'فحوصات صحة الأم والجنين — الغدة والسكر والحديد والعدوى (التوكسوبلازما والروبيلا) والفيتامينات والبول',
    price: 1350,
    discountedPrice: 799,
    badge: 'هرمونات',
    thumbnailUrl: '/packages/spec-pregnancy.webp',
    displayOrder: 31,
    isActive: true,
  },
  {
    id: '40',
    packageTypeId: '3',
    name: 'فحص الالتهابات الجنسية الأساسية',
    slug: 'std-basic',
    description:
      'فحص أساسي يغطي أهم الالتهابات الجنسية الشائعة — تحاليل دم ومسحات أساسية. يشمل زيارة منزلية مجاناً',
    price: 800,
    discountedPrice: 599,
    badge: 'صحة جنسية',
    thumbnailUrl: '/packages/std-basic.webp',
    displayOrder: 1,
    isActive: true,
  },
  {
    id: '41',
    packageTypeId: '3',
    name: 'فحص الأمراض المنقولة بتقنية PCR',
    slug: 'std-pcr',
    description:
      'فحص بتقنية PCR المتقدمة — أدق وأسرع في الكشف حتى في المراحل المبكرة. يشمل زيارة منزلية مجاناً',
    price: 900,
    discountedPrice: 599,
    badge: 'صحة جنسية',
    thumbnailUrl: '/packages/std-pcr.webp',
    displayOrder: 2,
    isActive: true,
  },
  {
    id: '42',
    packageTypeId: '3',
    name: 'باقة الكشف الشامل للأمراض المنقولة',
    slug: 'std-comprehensive',
    description:
      'أشمل باقة — تجمع تحاليل الدم + PCR + مسحات لكل الأمراض المنقولة. يشمل زيارة منزلية مجاناً',
    price: 2000,
    discountedPrice: 999,
    badge: 'صحة جنسية',
    thumbnailUrl: '/packages/std-comprehensive.webp',
    displayOrder: 3,
    isActive: true,
  },
  {
    id: '43',
    packageTypeId: '4',
    name: 'باقة الزواج الأساسية',
    slug: 'marriage',
    description: 'الفحص الإلزامي المعتمد في منصة صحتي لإتمام إجراءات الزواج',
    price: 499,
    badge: 'إلزامي',
    thumbnailUrl: '/packages/marriage.webp',
    displayOrder: 1,
    isActive: true,
  },
  {
    id: '44',
    packageTypeId: '4',
    name: 'الفحص الجيني ما قبل الزواج',
    slug: 'marriage-plus',
    description: 'تحليل جيني متقدم يكشف الأمراض الوراثية المحتملة لحماية صحة أجيالكم القادمة',
    price: 2999,
    badge: 'الأشمل',
    thumbnailUrl: '/packages/marriage-plus.webp',
    displayOrder: 2,
    isActive: true,
  },
  {
    id: '45',
    packageTypeId: '5',
    name: 'فحص NIPT C',
    slug: 'nipt-c',
    description: 'فحص جيني غير جراحي للكشف المبكر عن التثلث الصبغي — آمن للأم والجنين',
    price: 849,
    badge: 'كلاسيك',
    thumbnailUrl: '/packages/nipt-c.webp',
    displayOrder: 1,
    isActive: true,
  },
  {
    id: '46',
    packageTypeId: '5',
    name: 'فحص NIPT S',
    slug: 'nipt-s',
    description: 'فحص جيني شامل لجميع الكروموسومات مع الكشف عن متلازمات الحذف الدقيق',
    price: 999,
    badge: 'الأشمل',
    thumbnailUrl: '/packages/nipt-s-plus.webp',
    displayOrder: 2,
    isActive: true,
  },
]

const TEST_CATEGORIES: TestCategory[] = []
