/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones = 'Asia/Riyadh';

export interface Config {
  auth: {
    users: UserAuthOperations;
  };
  blocks: {};
  collections: {
    media: Media;
    'test-categories': TestCategory;
    tests: Test;
    'package-types': PackageType;
    'package-categories': PackageCategory;
    packages: Package;
    'blog-categories': BlogCategory;
    'blog-posts': BlogPost;
    'consultation-requests': ConsultationRequest;
    'consultation-time-slots': ConsultationTimeSlot;
    'consultation-schedule-templates': ConsultationScheduleTemplate;
    consultations: Consultation;
    'home-visit-requests': HomeVisitRequest;
    'home-visit-time-slots': HomeVisitTimeSlot;
    'home-visit-schedule-templates': HomeVisitScheduleTemplate;
    'home-visits': HomeVisit;
    'contact-messages': ContactMessage;
    'payload-kv': PayloadKv;
    users: User;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {
    'consultation-time-slots': {
      bookings: 'consultation-requests';
    };
    'home-visit-time-slots': {
      bookings: 'home-visit-requests';
    };
  };
  collectionsSelect: {
    media: MediaSelect<false> | MediaSelect<true>;
    'test-categories': TestCategoriesSelect<false> | TestCategoriesSelect<true>;
    tests: TestsSelect<false> | TestsSelect<true>;
    'package-types': PackageTypesSelect<false> | PackageTypesSelect<true>;
    'package-categories': PackageCategoriesSelect<false> | PackageCategoriesSelect<true>;
    packages: PackagesSelect<false> | PackagesSelect<true>;
    'blog-categories': BlogCategoriesSelect<false> | BlogCategoriesSelect<true>;
    'blog-posts': BlogPostsSelect<false> | BlogPostsSelect<true>;
    'consultation-requests': ConsultationRequestsSelect<false> | ConsultationRequestsSelect<true>;
    'consultation-time-slots': ConsultationTimeSlotsSelect<false> | ConsultationTimeSlotsSelect<true>;
    'consultation-schedule-templates': ConsultationScheduleTemplatesSelect<false> | ConsultationScheduleTemplatesSelect<true>;
    consultations: ConsultationsSelect<false> | ConsultationsSelect<true>;
    'home-visit-requests': HomeVisitRequestsSelect<false> | HomeVisitRequestsSelect<true>;
    'home-visit-time-slots': HomeVisitTimeSlotsSelect<false> | HomeVisitTimeSlotsSelect<true>;
    'home-visit-schedule-templates': HomeVisitScheduleTemplatesSelect<false> | HomeVisitScheduleTemplatesSelect<true>;
    'home-visits': HomeVisitsSelect<false> | HomeVisitsSelect<true>;
    'contact-messages': ContactMessagesSelect<false> | ContactMessagesSelect<true>;
    'payload-kv': PayloadKvSelect<false> | PayloadKvSelect<true>;
    users: UsersSelect<false> | UsersSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: string;
  };
  fallbackLocale: null;
  globals: {};
  globalsSelect: {};
  locale: null;
  widgets: {
    collections: CollectionsWidget;
  };
  user: User;
  jobs: {
    tasks: unknown;
    workflows: unknown;
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media".
 */
export interface Media {
  id: string;
  alt: string;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "test-categories".
 */
export interface TestCategory {
  id: string;
  name: string;
  /**
   * When enabled, the slug will auto-generate from the title field on save and autosave.
   */
  generateSlug?: boolean | null;
  slug: string;
  displayOrder?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "tests".
 */
export interface Test {
  id: string;
  name: string;
  badge?: string | null;
  /**
   * When enabled, the slug will auto-generate from the title field on save and autosave.
   */
  generateSlug?: boolean | null;
  slug: string;
  description?: string | null;
  price: number;
  individualSale?: boolean | null;
  testCategory?: (string | null) | TestCategory;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "package-types".
 */
export interface PackageType {
  id: string;
  name: string;
  /**
   * When enabled, the slug will auto-generate from the title field on save and autosave.
   */
  generateSlug?: boolean | null;
  slug: string;
  description?: string | null;
  headline?: string | null;
  subheadline?: string | null;
  color?: string | null;
  icon?: string | null;
  badge?: string | null;
  thumbnail?: (string | null) | Media;
  badges?:
    | {
        /**
         * الصق كود SVG كاملاً أو HTML. اتركه فارغاً لإظهار نقطة افتراضية.
         */
        customIcon?: string | null;
        text: string;
        id?: string | null;
      }[]
    | null;
  /**
   * إظهار خيارات البحث والتصفية حسب الفئة في صفحة الباقات
   */
  enableFiltering?: boolean | null;
  displayOrder?: number | null;
  isActive?: boolean | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "package-categories".
 */
export interface PackageCategory {
  id: string;
  name: string;
  /**
   * When enabled, the slug will auto-generate from the title field on save and autosave.
   */
  generateSlug?: boolean | null;
  slug: string;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "packages".
 */
export interface Package {
  id: string;
  name: string;
  /**
   * When enabled, the slug will auto-generate from the title field on save and autosave.
   */
  generateSlug?: boolean | null;
  slug: string;
  description?: string | null;
  price: number;
  discountedPrice?: number | null;
  badge?: string | null;
  thumbnail?: (string | null) | Media;
  displayOrder?: number | null;
  isActive?: boolean | null;
  packageType?: (string | null) | PackageType;
  packageCategory?: (string | null) | PackageCategory;
  /**
   * اختر التحاليل التي تريد إضافتها إلى هذه الباقة
   */
  tests?: (string | Test)[] | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "blog-categories".
 */
export interface BlogCategory {
  id: string;
  name: string;
  /**
   * When enabled, the slug will auto-generate from the title field on save and autosave.
   */
  generateSlug?: boolean | null;
  slug: string;
  description?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "blog-posts".
 */
export interface BlogPost {
  id: string;
  title: string;
  /**
   * When enabled, the slug will auto-generate from the title field on save and autosave.
   */
  generateSlug?: boolean | null;
  slug: string;
  featuredImage?: (string | null) | Media;
  excerpt?: string | null;
  content: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  };
  author?: string | null;
  category?: (string | null) | BlogCategory;
  tags?:
    | {
        tag?: string | null;
        id?: string | null;
      }[]
    | null;
  publishedAt?: string | null;
  status?: ('draft' | 'published') | null;
  faq?:
    | {
        question: string;
        answer: string;
        id?: string | null;
      }[]
    | null;
  meta?: {
    metaTitle?: string | null;
    metaDescription?: string | null;
    metaImage?: (string | null) | Media;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "consultation-requests".
 */
export interface ConsultationRequest {
  id: string;
  fullName: string;
  phoneNumber: string;
  consultationType: 'pre_analysis' | 'results_review';
  slot: string | ConsultationTimeSlot;
  status?: ('pending' | 'confirmed' | 'cancelled' | 'completed') | null;
  referenceNumber?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "consultation-time-slots".
 */
export interface ConsultationTimeSlot {
  id: string;
  date: string;
  startTime: string;
  endTime: string;
  maxCapacity: number;
  /**
   * عند الوصول للسعة القصوى، سيتم تغيير الحالة إلى "ممتلئ" تلقائياً
   */
  autoCloseWhenFull?: boolean | null;
  availabilityStatus?: ('available' | 'full' | 'manually_closed') | null;
  bookedCount?: number | null;
  remainingCapacity?: number | null;
  displayTitle?: string | null;
  bookings?: {
    docs?: (string | ConsultationRequest)[];
    hasNextPage?: boolean;
    totalDocs?: number;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * قم بإنشاء نموذج أسبوعي للمواعيد ثم توليده تلقائياً
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "consultation-schedule-templates".
 */
export interface ConsultationScheduleTemplate {
  id: string;
  /**
   * مثال: جدول العيادة الصباحي - رمضان 2026
   */
  name: string;
  /**
   * أول يوم يبدأ فيه تطبيق النموذج
   */
  startDate: string;
  /**
   * آخر يوم ينتهي فيه تطبيق النموذج
   */
  endDate: string;
  /**
   * حدد أيام الأسبوع وفترات الوقت المتاحة لكل يوم
   */
  schedule: {
    dayOfWeek: '0' | '1' | '2' | '3' | '4' | '5' | '6';
    timeSlots: {
      startTime: string;
      endTime: string;
      maxCapacity: number;
      autoCloseWhenFull?: boolean | null;
      id?: string | null;
    }[];
    id?: string | null;
  }[];
  /**
   * يتم تحديثه تلقائياً بعد كل عملية توليد ناجحة
   */
  lastGeneratedAt?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "consultations".
 */
export interface Consultation {
  id: string;
  consultationRequest: string | ConsultationRequest;
  status?: ('scheduled' | 'in_progress' | 'completed' | 'no_show' | 'cancelled') | null;
  chiefComplaint?: string | null;
  notes?: string | null;
  diagnosis?: string | null;
  treatmentPlan?: string | null;
  prescriptions?:
    | {
        medicationName: string;
        dosage?: string | null;
        frequency?: string | null;
        duration?: string | null;
        instructions?: string | null;
        id?: string | null;
      }[]
    | null;
  attachments?:
    | {
        file?: (string | null) | Media;
        description?: string | null;
        id?: string | null;
      }[]
    | null;
  followUpRequired?: boolean | null;
  followUpDate?: string | null;
  completedAt?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "home-visit-requests".
 */
export interface HomeVisitRequest {
  id: string;
  fullName: string;
  phoneNumber: string;
  slot: string | HomeVisitTimeSlot;
  status?: ('pending' | 'confirmed' | 'cancelled' | 'completed') | null;
  referenceNumber?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "home-visit-time-slots".
 */
export interface HomeVisitTimeSlot {
  id: string;
  date: string;
  startTime: string;
  endTime: string;
  maxCapacity: number;
  /**
   * عند الوصول للسعة القصوى، سيتم تغيير الحالة إلى "ممتلئ" تلقائياً
   */
  autoCloseWhenFull?: boolean | null;
  availabilityStatus?: ('available' | 'full' | 'manually_closed') | null;
  bookedCount?: number | null;
  remainingCapacity?: number | null;
  displayTitle?: string | null;
  bookings?: {
    docs?: (string | HomeVisitRequest)[];
    hasNextPage?: boolean;
    totalDocs?: number;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * قم بإنشاء نموذج أسبوعي للمواعيد ثم توليده تلقائياً
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "home-visit-schedule-templates".
 */
export interface HomeVisitScheduleTemplate {
  id: string;
  /**
   * مثال: جدول العيادة الصباحي - رمضان 2026
   */
  name: string;
  /**
   * أول يوم يبدأ فيه تطبيق النموذج
   */
  startDate: string;
  /**
   * آخر يوم ينتهي فيه تطبيق النموذج
   */
  endDate: string;
  /**
   * حدد أيام الأسبوع وفترات الوقت المتاحة لكل يوم
   */
  schedule: {
    dayOfWeek: '0' | '1' | '2' | '3' | '4' | '5' | '6';
    timeSlots: {
      startTime: string;
      endTime: string;
      maxCapacity: number;
      autoCloseWhenFull?: boolean | null;
      id?: string | null;
    }[];
    id?: string | null;
  }[];
  /**
   * يتم تحديثه تلقائياً بعد كل عملية توليد ناجحة
   */
  lastGeneratedAt?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "home-visits".
 */
export interface HomeVisit {
  id: string;
  homeVisitRequest: string | HomeVisitRequest;
  status?: ('scheduled' | 'in_progress' | 'completed' | 'cancelled') | null;
  chiefComplaint?: string | null;
  notes?: string | null;
  diagnosis?: string | null;
  treatmentPlan?: string | null;
  prescriptions?:
    | {
        medicationName: string;
        dosage?: string | null;
        frequency?: string | null;
        duration?: string | null;
        instructions?: string | null;
        id?: string | null;
      }[]
    | null;
  attachments?:
    | {
        file?: (string | null) | Media;
        description?: string | null;
        id?: string | null;
      }[]
    | null;
  followUpRequired?: boolean | null;
  followUpDate?: string | null;
  completedAt?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "contact-messages".
 */
export interface ContactMessage {
  id: string;
  fullName: string;
  phoneNumber: string;
  message?: string | null;
  status?: ('new' | 'read' | 'replied' | 'archived') | null;
  notes?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv".
 */
export interface PayloadKv {
  id: string;
  key: string;
  data:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: string;
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
  collection: 'users';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: string;
  document?:
    | ({
        relationTo: 'media';
        value: string | Media;
      } | null)
    | ({
        relationTo: 'test-categories';
        value: string | TestCategory;
      } | null)
    | ({
        relationTo: 'tests';
        value: string | Test;
      } | null)
    | ({
        relationTo: 'package-types';
        value: string | PackageType;
      } | null)
    | ({
        relationTo: 'package-categories';
        value: string | PackageCategory;
      } | null)
    | ({
        relationTo: 'packages';
        value: string | Package;
      } | null)
    | ({
        relationTo: 'blog-categories';
        value: string | BlogCategory;
      } | null)
    | ({
        relationTo: 'blog-posts';
        value: string | BlogPost;
      } | null)
    | ({
        relationTo: 'consultation-requests';
        value: string | ConsultationRequest;
      } | null)
    | ({
        relationTo: 'consultation-time-slots';
        value: string | ConsultationTimeSlot;
      } | null)
    | ({
        relationTo: 'consultation-schedule-templates';
        value: string | ConsultationScheduleTemplate;
      } | null)
    | ({
        relationTo: 'consultations';
        value: string | Consultation;
      } | null)
    | ({
        relationTo: 'home-visit-requests';
        value: string | HomeVisitRequest;
      } | null)
    | ({
        relationTo: 'home-visit-time-slots';
        value: string | HomeVisitTimeSlot;
      } | null)
    | ({
        relationTo: 'home-visit-schedule-templates';
        value: string | HomeVisitScheduleTemplate;
      } | null)
    | ({
        relationTo: 'home-visits';
        value: string | HomeVisit;
      } | null)
    | ({
        relationTo: 'contact-messages';
        value: string | ContactMessage;
      } | null)
    | ({
        relationTo: 'users';
        value: string | User;
      } | null);
  globalSlug?: string | null;
  user: {
    relationTo: 'users';
    value: string | User;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: string;
  user: {
    relationTo: 'users';
    value: string | User;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: string;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media_select".
 */
export interface MediaSelect<T extends boolean = true> {
  alt?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "test-categories_select".
 */
export interface TestCategoriesSelect<T extends boolean = true> {
  name?: T;
  generateSlug?: T;
  slug?: T;
  displayOrder?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "tests_select".
 */
export interface TestsSelect<T extends boolean = true> {
  name?: T;
  badge?: T;
  generateSlug?: T;
  slug?: T;
  description?: T;
  price?: T;
  individualSale?: T;
  testCategory?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "package-types_select".
 */
export interface PackageTypesSelect<T extends boolean = true> {
  name?: T;
  generateSlug?: T;
  slug?: T;
  description?: T;
  headline?: T;
  subheadline?: T;
  color?: T;
  icon?: T;
  badge?: T;
  thumbnail?: T;
  badges?:
    | T
    | {
        customIcon?: T;
        text?: T;
        id?: T;
      };
  enableFiltering?: T;
  displayOrder?: T;
  isActive?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "package-categories_select".
 */
export interface PackageCategoriesSelect<T extends boolean = true> {
  name?: T;
  generateSlug?: T;
  slug?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "packages_select".
 */
export interface PackagesSelect<T extends boolean = true> {
  name?: T;
  generateSlug?: T;
  slug?: T;
  description?: T;
  price?: T;
  discountedPrice?: T;
  badge?: T;
  thumbnail?: T;
  displayOrder?: T;
  isActive?: T;
  packageType?: T;
  packageCategory?: T;
  tests?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "blog-categories_select".
 */
export interface BlogCategoriesSelect<T extends boolean = true> {
  name?: T;
  generateSlug?: T;
  slug?: T;
  description?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "blog-posts_select".
 */
export interface BlogPostsSelect<T extends boolean = true> {
  title?: T;
  generateSlug?: T;
  slug?: T;
  featuredImage?: T;
  excerpt?: T;
  content?: T;
  author?: T;
  category?: T;
  tags?:
    | T
    | {
        tag?: T;
        id?: T;
      };
  publishedAt?: T;
  status?: T;
  faq?:
    | T
    | {
        question?: T;
        answer?: T;
        id?: T;
      };
  meta?:
    | T
    | {
        metaTitle?: T;
        metaDescription?: T;
        metaImage?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "consultation-requests_select".
 */
export interface ConsultationRequestsSelect<T extends boolean = true> {
  fullName?: T;
  phoneNumber?: T;
  consultationType?: T;
  slot?: T;
  status?: T;
  referenceNumber?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "consultation-time-slots_select".
 */
export interface ConsultationTimeSlotsSelect<T extends boolean = true> {
  date?: T;
  startTime?: T;
  endTime?: T;
  maxCapacity?: T;
  autoCloseWhenFull?: T;
  availabilityStatus?: T;
  bookedCount?: T;
  remainingCapacity?: T;
  displayTitle?: T;
  bookings?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "consultation-schedule-templates_select".
 */
export interface ConsultationScheduleTemplatesSelect<T extends boolean = true> {
  name?: T;
  startDate?: T;
  endDate?: T;
  schedule?:
    | T
    | {
        dayOfWeek?: T;
        timeSlots?:
          | T
          | {
              startTime?: T;
              endTime?: T;
              maxCapacity?: T;
              autoCloseWhenFull?: T;
              id?: T;
            };
        id?: T;
      };
  lastGeneratedAt?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "consultations_select".
 */
export interface ConsultationsSelect<T extends boolean = true> {
  consultationRequest?: T;
  status?: T;
  chiefComplaint?: T;
  notes?: T;
  diagnosis?: T;
  treatmentPlan?: T;
  prescriptions?:
    | T
    | {
        medicationName?: T;
        dosage?: T;
        frequency?: T;
        duration?: T;
        instructions?: T;
        id?: T;
      };
  attachments?:
    | T
    | {
        file?: T;
        description?: T;
        id?: T;
      };
  followUpRequired?: T;
  followUpDate?: T;
  completedAt?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "home-visit-requests_select".
 */
export interface HomeVisitRequestsSelect<T extends boolean = true> {
  fullName?: T;
  phoneNumber?: T;
  slot?: T;
  status?: T;
  referenceNumber?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "home-visit-time-slots_select".
 */
export interface HomeVisitTimeSlotsSelect<T extends boolean = true> {
  date?: T;
  startTime?: T;
  endTime?: T;
  maxCapacity?: T;
  autoCloseWhenFull?: T;
  availabilityStatus?: T;
  bookedCount?: T;
  remainingCapacity?: T;
  displayTitle?: T;
  bookings?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "home-visit-schedule-templates_select".
 */
export interface HomeVisitScheduleTemplatesSelect<T extends boolean = true> {
  name?: T;
  startDate?: T;
  endDate?: T;
  schedule?:
    | T
    | {
        dayOfWeek?: T;
        timeSlots?:
          | T
          | {
              startTime?: T;
              endTime?: T;
              maxCapacity?: T;
              autoCloseWhenFull?: T;
              id?: T;
            };
        id?: T;
      };
  lastGeneratedAt?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "home-visits_select".
 */
export interface HomeVisitsSelect<T extends boolean = true> {
  homeVisitRequest?: T;
  status?: T;
  chiefComplaint?: T;
  notes?: T;
  diagnosis?: T;
  treatmentPlan?: T;
  prescriptions?:
    | T
    | {
        medicationName?: T;
        dosage?: T;
        frequency?: T;
        duration?: T;
        instructions?: T;
        id?: T;
      };
  attachments?:
    | T
    | {
        file?: T;
        description?: T;
        id?: T;
      };
  followUpRequired?: T;
  followUpDate?: T;
  completedAt?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "contact-messages_select".
 */
export interface ContactMessagesSelect<T extends boolean = true> {
  fullName?: T;
  phoneNumber?: T;
  message?: T;
  status?: T;
  notes?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv_select".
 */
export interface PayloadKvSelect<T extends boolean = true> {
  key?: T;
  data?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "collections_widget".
 */
export interface CollectionsWidget {
  data?: {
    [k: string]: unknown;
  };
  width: 'full';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}